# Generated by Django 2.2.2 on 2020-12-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='place',
        ),
    ]
